# Generated by Django 5.2.3 on 2025-07-08 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavedetails',
            old_name='status',
            new_name='leave_status',
        ),
    ]
