# Generated by Django 5.2.3 on 2025-09-21 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
