# Generated by Django 5.2.3 on 2025-09-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
