# Generated by Django 5.2.5 on 2025-10-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_leavedetails_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavedetails',
            name='reason_leave',
        ),
    ]
