# Generated by Django 5.2.5 on 2025-10-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_leavedetails_reason_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavedetails',
            name='deadline_for_docs',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
