# Generated by Django 5.2.3 on 2025-09-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phoneNumber',
            field=models.CharField(default='0000-000-0000', max_length=20),
        ),
    ]
